"""Tests for the version/hash stamp on config.effective.yml (issue #279, PR-4).

``config.effective.yml`` is a DERIVED artifact (a projection of
``config.yml`` x ``defaults.py`` x ``fabric.json``). PR-4 stamps it with a
dedicated ``_effective_config_meta`` block carrying the schema version and the
sha256 of the *verbatim* ``config.yml`` bytes, so a stale effective config is a
*detected* inconsistency the publish gate can refuse on -- never silent drift.
"""

from __future__ import annotations

import hashlib
from pathlib import Path

import yaml


def _make_project(tmp_path: Path) -> Path:
    """A workdir with a ``config.yml`` sufficient for ``_write_effective_config``."""
    workdir = tmp_path / "proj"
    workdir.mkdir()
    (workdir / "config.yml").write_text(
        yaml.safe_dump(
            {
                "datastore": str(tmp_path / "store"),
                "fabric": {
                    "path": str(tmp_path / "fabric.gpkg"),
                    "id_col": "nhm_id",
                },
            }
        )
    )
    return workdir


def test_effective_config_carries_meta_block(tmp_path: Path):
    from nhf_spatial_targets.defaults import apply_defaults
    from nhf_spatial_targets.validate import (
        EFFECTIVE_CONFIG_SCHEMA_VERSION,
        _write_effective_config,
    )

    workdir = _make_project(tmp_path)
    user_cfg = yaml.safe_load((workdir / "config.yml").read_text())
    _write_effective_config(workdir, apply_defaults(user_cfg))

    body = yaml.safe_load((workdir / "config.effective.yml").read_text())
    meta = body["_effective_config_meta"]
    assert meta["effective_config_schema_version"] == EFFECTIVE_CONFIG_SCHEMA_VERSION
    assert EFFECTIVE_CONFIG_SCHEMA_VERSION == 1
    # Exactly two keys -- pins "no wall-clock timestamp" (a future generated_at
    # field would break this) and the reproducible meta shape.
    assert set(meta) == {"effective_config_schema_version", "source_config_sha256"}


def test_source_config_sha256_matches_verbatim_config_bytes(tmp_path: Path):
    from nhf_spatial_targets.defaults import apply_defaults
    from nhf_spatial_targets.validate import _write_effective_config

    workdir = _make_project(tmp_path)
    config_bytes = (workdir / "config.yml").read_bytes()
    user_cfg = yaml.safe_load((workdir / "config.yml").read_text())
    _write_effective_config(workdir, apply_defaults(user_cfg))

    body = yaml.safe_load((workdir / "config.effective.yml").read_text())
    assert (
        body["_effective_config_meta"]["source_config_sha256"]
        == hashlib.sha256(config_bytes).hexdigest()
    )


def test_effective_config_is_reproducible(tmp_path: Path):
    """No wall-clock timestamp: two writes on an unchanged config.yml produce
    byte-identical output (locks out any future generated_at-style field that
    would silently defeat the version/hash staleness check)."""
    from nhf_spatial_targets.defaults import apply_defaults
    from nhf_spatial_targets.validate import _write_effective_config

    workdir = _make_project(tmp_path)
    user_cfg = yaml.safe_load((workdir / "config.yml").read_text())
    _write_effective_config(workdir, apply_defaults(user_cfg))
    first = (workdir / "config.effective.yml").read_text()
    _write_effective_config(workdir, apply_defaults(user_cfg))
    second = (workdir / "config.effective.yml").read_text()
    assert first == second


def test_meta_block_not_leaked_into_merged_dict(tmp_path: Path):
    """The live merged dict is reused downstream (manifest step params,
    ``_write_manifest``); the meta block must be injected into a COPY only."""
    from nhf_spatial_targets.defaults import apply_defaults
    from nhf_spatial_targets.validate import _write_effective_config

    workdir = _make_project(tmp_path)
    user_cfg = yaml.safe_load((workdir / "config.yml").read_text())
    merged = apply_defaults(user_cfg)
    _write_effective_config(workdir, merged)
    assert "_effective_config_meta" not in merged


def test_existing_config_keys_survive_alongside_meta(tmp_path: Path):
    """Adding the meta block must not drop or alter the merged config body, and
    the ``# AUTOGENERATED`` header must remain the first line."""
    from nhf_spatial_targets.defaults import apply_defaults
    from nhf_spatial_targets.validate import _write_effective_config

    workdir = _make_project(tmp_path)
    user_cfg = yaml.safe_load((workdir / "config.yml").read_text())
    _write_effective_config(workdir, apply_defaults(user_cfg))

    text = (workdir / "config.effective.yml").read_text()
    assert text.startswith("# AUTOGENERATED")
    body = yaml.safe_load(text)
    assert body["fabric"]["area_crs"] == "EPSG:5070"
    assert body["targets"]["runoff"]["nn_fill"] is True
