"""Tests for the validate-time defaults diff and config.effective.yml."""

from __future__ import annotations

import platform
from pathlib import Path

import pytest
import yaml


def _make_minimal_project(tmp_path: Path) -> Path:
    """Skeleton sufficient for the defaults/effective-config code paths.

    Skips the full validate path (fabric/credentials) by directly invoking
    the pure-config helpers exposed by the validate module.
    """
    workdir = tmp_path / "proj"
    workdir.mkdir()
    (workdir / "config.yml").write_text(
        yaml.safe_dump(
            {
                "datastore": str(tmp_path / "store"),
                "fabric": {
                    "path": str(tmp_path / "fabric.gpkg"),
                    "id_col": "nhm_id",
                },
            }
        )
    )
    return workdir


def test_report_defaults_diff_lists_filled_keys(tmp_path: Path, capsys):
    from nhf_spatial_targets.validate import _report_defaults_and_unknowns

    workdir = _make_minimal_project(tmp_path)
    user_cfg = yaml.safe_load((workdir / "config.yml").read_text())
    _report_defaults_and_unknowns(user_cfg)
    err = capsys.readouterr().err
    assert "[defaults] fabric.area_crs" in err
    assert "[defaults] targets.runoff.nn_fill" in err


def test_report_unknown_keys_warns(tmp_path: Path, capsys):
    from nhf_spatial_targets.validate import _report_defaults_and_unknowns

    user_cfg = {
        "datastore": "/d",
        "fabric": {"path": "/p", "id_col": "nhm_id"},
        "targets": {"runoff": {"nn_fil": True}},  # typo
    }
    _report_defaults_and_unknowns(user_cfg)
    err = capsys.readouterr().err
    assert "[warning] unknown config key: targets.runoff.nn_fil" in err


def test_write_effective_config_writes_merged_yaml(tmp_path: Path):
    from nhf_spatial_targets.validate import _write_effective_config

    workdir = _make_minimal_project(tmp_path)
    user_cfg = yaml.safe_load((workdir / "config.yml").read_text())
    _write_effective_config(workdir, user_cfg)

    out = workdir / "config.effective.yml"
    assert out.exists()
    text = out.read_text()
    assert text.startswith("# AUTOGENERATED")
    body = yaml.safe_load(text)
    assert body["fabric"]["area_crs"] == "EPSG:5070"
    assert body["targets"]["runoff"]["sources"] == [
        "era5_land",
        "gldas_noah_v21_monthly",
        "mwbm_climgrid",
    ]


@pytest.mark.skipif(platform.system() == "Windows", reason="POSIX file modes only")
def test_write_effective_config_is_read_only(tmp_path: Path):
    from nhf_spatial_targets.validate import _write_effective_config

    workdir = _make_minimal_project(tmp_path)
    user_cfg = yaml.safe_load((workdir / "config.yml").read_text())
    _write_effective_config(workdir, user_cfg)

    mode = (workdir / "config.effective.yml").stat().st_mode & 0o777
    assert mode == 0o444


def test_write_effective_config_overwrites_existing(tmp_path: Path):
    """Read-only mode on the existing file must not block re-write."""
    from nhf_spatial_targets.validate import _write_effective_config

    workdir = _make_minimal_project(tmp_path)
    user_cfg = yaml.safe_load((workdir / "config.yml").read_text())
    _write_effective_config(workdir, user_cfg)

    # Mutate the user config and write again — must succeed.
    user_cfg["fabric"]["area_crs"] = "EPSG:3338"
    _write_effective_config(workdir, user_cfg)
    body = yaml.safe_load((workdir / "config.effective.yml").read_text())
    assert body["fabric"]["area_crs"] == "EPSG:3338"


def test_check_required_raises_on_missing_period(tmp_path: Path):
    from nhf_spatial_targets.validate import _check_required_keys

    user_cfg = {
        "datastore": "/d",
        "fabric": {"path": "/p", "id_col": "nhm_id"},
        # runoff.enabled True by default; no period -> should raise
    }
    with pytest.raises(ValueError, match="targets.runoff.period"):
        _check_required_keys(user_cfg)
