"""Preflight validation for an nhf-spatial-targets project."""

from __future__ import annotations

import hashlib
import json
import logging
import os
import platform
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path

import yaml

from nhf_spatial_targets import __version__
from nhf_spatial_targets.workspace import make_dir

logger = logging.getLogger(__name__)

# The source keys whose raw-data subdirectories are created.
_SOURCE_KEYS: list[str] = [
    "era5_land",
    "gldas_noah_v21_monthly",
    "merra2",
    "nldas_mosaic",
    "nldas_noah",
    "ncep_ncar",
    "mod16a2_v061",
    "mod10c1_v061",
    "watergap22d",
    "reitz2017",
]


# ---------------------------------------------------------------------------
# Config helpers (defaults diff, unknown-key warnings, effective config)
# ---------------------------------------------------------------------------


def _report_defaults_and_unknowns(user_cfg: dict | None) -> None:
    """Print to stderr which keys took defaults and which are unknown.

    Called once per ``validate`` run so the user sees the migration impact
    of new defaulted keys without their on-disk config being modified.
    """
    from nhf_spatial_targets.defaults import find_unknown_keys, iter_default_diff

    for path, value in iter_default_diff(user_cfg):
        print(f"[defaults] {path} not set; using default: {value!r}", file=sys.stderr)
    for path in find_unknown_keys(user_cfg):
        print(
            f"[warning] unknown config key: {path} (typo? not in defaults schema)",
            file=sys.stderr,
        )


def _check_required_keys(user_cfg: dict | None) -> dict:
    """Apply defaults and raise if any required keys are missing.

    Returns the merged config so callers can re-use it without re-merging.
    """
    from nhf_spatial_targets.defaults import apply_defaults, missing_required

    merged = apply_defaults(user_cfg)
    missing = missing_required(merged)
    if missing:
        raise ValueError(
            "Required config keys missing or empty:\n  - "
            + "\n  - ".join(missing)
            + "\nEdit config.yml and re-run validate."
        )
    return merged


def _write_effective_config(workdir: Path, merged: dict) -> Path:
    """Write the fully-merged config to ``<workdir>/config.effective.yml``.

    Caller passes the already-merged dict (from ``_check_required_keys``)
    so this helper is purely a writer with no policy coupled in.

    Always rewritten on every validate run; mode 0o444 so manual edits
    get a clear permission error (the source-of-truth file is
    ``config.yml``). The existing file is unlinked first so the
    read-only mode does not block the re-write.
    """
    body = (
        "# AUTOGENERATED by nhf-targets validate. Do not edit; edit config.yml.\n"
        + yaml.safe_dump(merged, sort_keys=False)
    )
    out = workdir / "config.effective.yml"
    if out.exists():
        # Windows blocks DeleteFile on read-only files; chmod to writable
        # before unlink. POSIX would unlink fine regardless (the dir mode
        # governs unlink, not the file mode), but the chmod is harmless.
        out.chmod(0o644)
        out.unlink()
    out.write_text(body)
    if platform.system() != "Windows":
        out.chmod(0o444)
    return out


# ---------------------------------------------------------------------------
# Public entry points
# ---------------------------------------------------------------------------


def validate_credentials(path: Path, required: list[str]) -> None:
    """Validate that *path* contains all *required* credential sections.

    Supported section names:

    - ``"nasa_earthdata"`` — requires non-empty ``username`` and ``password``
    - ``"cds"`` — requires non-empty ``url`` and ``key``

    Raises ``ValueError`` naming the missing or incomplete section.
    """
    path = Path(path)
    if not path.exists():
        raise FileNotFoundError(
            f".credentials.yml not found: {path}. "
            "Create it with the required credentials before validating."
        )
    try:
        creds = yaml.safe_load(path.read_text()) or {}
    except yaml.YAMLError as exc:
        raise ValueError(f"Cannot parse {path}: {exc}") from exc

    for name in required:
        section = creds.get(name, {}) or {}
        if name == "nasa_earthdata":
            if not section.get("username") or not section.get("password"):
                raise ValueError(
                    f"Ensure the 'nasa_earthdata' section of {path} is populated, "
                    "then run:\n"
                    f"    nhf-targets materialize-credentials "
                    f"--project-dir {path.parent}\n\n"
                    f"Earthdata credentials incomplete — "
                    f"nasa_earthdata.username and nasa_earthdata.password "
                    f"must be non-empty in {path.name}"
                )
        elif name == "cds":
            if not section.get("url") or not section.get("key"):
                raise ValueError(
                    f"Ensure the 'cds' section of {path} is populated, "
                    "then run:\n"
                    f"    nhf-targets materialize-credentials "
                    f"--project-dir {path.parent}\n\n"
                    f"cds credentials incomplete — "
                    f"cds.url and cds.key must be non-empty in {path.name}"
                )
        else:
            raise ValueError(f"Unknown credential section: '{name}'")


def validate_workspace(workdir: Path) -> None:
    """Run preflight checks on a project directory, failing fast on errors.

    On success, writes ``fabric.json``, ``manifest.json``, and
    ``config.effective.yml`` into *workdir*. Reports default-application
    and unknown-key warnings to stderr.
    """
    workdir = Path(workdir).resolve()

    # 0. Load raw user config (without merging defaults yet — we want to know
    #    what the user set vs. what came from defaults).
    config_path = workdir / "config.yml"
    if not config_path.exists():
        raise FileNotFoundError(
            f"config.yml not found in {workdir}. "
            f"Run 'nhf-targets init --project-dir {workdir}' first."
        )
    try:
        user_cfg = yaml.safe_load(config_path.read_text())
    except yaml.YAMLError as exc:
        raise ValueError(f"Cannot parse config.yml in {workdir}: {exc}") from exc
    if user_cfg is None:
        raise ValueError(
            f"config.yml in {workdir} is empty. It must contain YAML key-value pairs."
        )
    if not isinstance(user_cfg, dict):
        raise ValueError(
            f"config.yml in {workdir} is malformed. "
            f"It must contain YAML key-value pairs."
        )

    # 1. Report defaults diff and unknown keys (informational), then
    #    enforce required-key presence on the merged result.
    _report_defaults_and_unknowns(user_cfg)
    config = _check_required_keys(user_cfg)

    # 2. Fabric exists
    fabric_path = Path(config["fabric"]["path"])
    id_col = config["fabric"]["id_col"]
    _check_fabric_exists(fabric_path)

    # 3-4. Fabric metadata (sha256, bbox, hru_count) + id_col check
    buffer_deg = float(config["fabric"]["buffer_deg"])
    fabric_meta = _fabric_metadata(fabric_path, id_col, buffer_deg)

    # 5. Credentials
    _check_credentials(workdir)

    # 6. Datastore — create directory tree
    datastore = Path(config["datastore"])
    dir_mode_str = config.get("dir_mode")
    dir_mode = int(dir_mode_str, 8) if dir_mode_str else None
    _ensure_datastore(datastore, dir_mode)

    # 7. Catalog consistency
    _check_catalog_consistency()

    # Write outputs
    _write_fabric_json(workdir, fabric_meta)
    _write_manifest(workdir, fabric_meta)
    _write_effective_config(
        workdir, config
    )  # config is the merged dict from _check_required_keys


# ---------------------------------------------------------------------------
# Step helpers
# ---------------------------------------------------------------------------


def _check_fabric_exists(fabric_path: Path) -> None:
    if not fabric_path.exists():
        raise FileNotFoundError(f"Fabric file not found: {fabric_path}")


def _check_id_column(gdf: object, id_col: str) -> None:
    """Check that id_col exists in a loaded GeoDataFrame."""
    if id_col not in gdf.columns:
        raise ValueError(
            f"Column '{id_col}' not found in fabric. "
            f"Available columns: {list(gdf.columns)}"
        )


def _import_cdsapi() -> None:
    """Attempt to import cdsapi; raise ValueError if not installed."""
    try:
        import cdsapi  # noqa: F401
    except ImportError as exc:
        raise ValueError(
            "cdsapi is required for Copernicus CDS sources but is not installed. "
            "Install it with: pip install cdsapi"
        ) from exc


def _check_cdsapirc(_home: Path | None = None) -> None:
    """Check that ~/.cdsapirc exists so cdsapi can authenticate.

    Raises ``ValueError`` with a clear remediation message if the file is
    missing.  Does not validate the content — cdsapi itself will error at
    request time with a more specific message if the key is wrong.

    Parameters
    ----------
    _home : Path | None
        Override the home directory (used in tests). Defaults to
        ``Path.home()``.
    """
    home = _home if _home is not None else Path.home()
    cdsapirc = home / ".cdsapirc"
    if not cdsapirc.exists():
        raise ValueError(
            "CDS credentials are required but ~/.cdsapirc was not found. "
            "Fill in the 'cds' section of .credentials.yml and run:\n\n"
            "  nhf-targets materialize-credentials --project-dir <project-dir>\n\n"
            "This will write ~/.cdsapirc automatically.  Alternatively, create "
            "it manually:\n\n"
            "  url: https://cds.climate.copernicus.eu/api\n"
            "  key: <your-api-key>\n\n"
            "Obtain an API key from https://cds.climate.copernicus.eu "
            "after registering and accepting the Terms of Use."
        )


def _check_netrc_earthdata(_home: Path | None = None) -> None:
    """Check that ~/.netrc has an entry for urs.earthdata.nasa.gov.

    Raises ``ValueError`` with a clear remediation message if the entry is
    absent.  Does not validate the credentials — earthaccess will produce its
    own error at download time if they are incorrect.

    Parameters
    ----------
    _home : Path | None
        Override the home directory (used in tests). Defaults to
        ``Path.home()``.
    """
    home = _home if _home is not None else Path.home()
    netrc_path = home / ".netrc"
    if not netrc_path.exists():
        raise ValueError(
            "NASA Earthdata credentials are required but ~/.netrc was not found. "
            "Fill in the 'nasa_earthdata' section of .credentials.yml and run:\n\n"
            "  nhf-targets materialize-credentials --project-dir <project-dir>\n\n"
            "This will write ~/.netrc automatically.  Alternatively, create it "
            "manually:\n\n"
            "  machine urs.earthdata.nasa.gov login <user> password <password>\n\n"
            "Register at https://urs.earthdata.nasa.gov to obtain credentials."
        )
    content = netrc_path.read_text()
    if "urs.earthdata.nasa.gov" not in content:
        raise ValueError(
            "~/.netrc exists but does not contain an entry for "
            "urs.earthdata.nasa.gov. Fill in .credentials.yml and run:\n\n"
            "  nhf-targets materialize-credentials --project-dir <project-dir>\n\n"
            "Or add the entry manually:\n\n"
            "  machine urs.earthdata.nasa.gov login <user> password <password>\n\n"
            "See https://urs.earthdata.nasa.gov for registration."
        )


def _check_credentials(workdir: Path) -> None:
    cred_path = workdir / ".credentials.yml"

    # Build the required list: always need nasa_earthdata; add cds if catalog requires it
    from nhf_spatial_targets.catalog import sources as catalog_sources

    srcs = catalog_sources()
    required: list[str] = ["nasa_earthdata"]
    needs_cds = any(
        (src.get("access") or {}).get("type") == "copernicus_cds"
        for src in srcs.values()
    )
    # Every NASA-Earthdata-authenticated `access.type` value used in the
    # catalog. Keep in sync with the fetch modules — any new EDL-using
    # type needs to be added here so `nhf-targets validate` still
    # catches missing creds before the operator hits a runtime auth
    # failure inside earthaccess. `nasa_nsidc` is retained as a defensive
    # fallback for historical entries even though current entries use
    # the cleaner `nsidc` / `nsidc_https` tags.
    _EDL_TYPES = (
        "nasa_gesdisc",
        "nasa_earthdata",
        "nasa_nsidc",
        "nsidc",
        "nsidc_https",
        "lpdaac",
    )
    needs_earthdata = any(
        (src.get("access") or {}).get("type") in _EDL_TYPES for src in srcs.values()
    )
    if needs_cds:
        required.append("cds")
        _import_cdsapi()

    validate_credentials(cred_path, required=required)

    # Preflight: check that system credential files exist so tools can authenticate.
    if needs_cds:
        _check_cdsapirc()
    if needs_earthdata or "nasa_earthdata" in required:
        _check_netrc_earthdata()


def _ensure_datastore(datastore: Path, dir_mode: int | None) -> None:
    make_dir(datastore, dir_mode=dir_mode)
    for key in _SOURCE_KEYS:
        make_dir(datastore / key, dir_mode=dir_mode)


def _check_catalog_consistency() -> None:
    from nhf_spatial_targets.catalog import sources, variables

    src_keys = set(sources().keys())
    for var_name, var_def in variables().items():
        for src in var_def.get("sources", []):
            if src not in src_keys:
                raise ValueError(
                    f"Variable '{var_name}' references source '{src}' "
                    f"which does not exist in catalog/sources.yml"
                )


# ---------------------------------------------------------------------------
# Fabric metadata (moved from init_run.py)
# ---------------------------------------------------------------------------


def _fabric_metadata(fabric_path: Path, id_col: str, buffer_deg: float) -> dict:
    """Compute fabric hash, bbox, and HRU count. Also validates id_col."""
    import geopandas as gpd
    from shapely.geometry import box

    sha256 = _sha256(fabric_path)

    if fabric_path.suffix.lower() in (".parquet", ".geoparquet"):
        gdf = gpd.read_parquet(fabric_path)
    else:
        gdf = gpd.read_file(fabric_path, rows=None)
    # Check id_col here to avoid reading the fabric twice
    _check_id_column(gdf, id_col)

    native_crs = gdf.crs.to_string() if gdf.crs else "unknown"
    hru_count = len(gdf)

    native_bounds = gdf.total_bounds
    if gdf.crs and not gdf.crs.is_geographic:
        bbox_geom = gpd.GeoSeries([box(*native_bounds)], crs=gdf.crs)
        wgs84_bounds = bbox_geom.to_crs("EPSG:4326").total_bounds
    else:
        wgs84_bounds = native_bounds

    buffered = {
        "minx": float(wgs84_bounds[0]) - buffer_deg,
        "miny": float(wgs84_bounds[1]) - buffer_deg,
        "maxx": float(wgs84_bounds[2]) + buffer_deg,
        "maxy": float(wgs84_bounds[3]) + buffer_deg,
    }

    return {
        "path": str(fabric_path),
        "sha256": sha256,
        "crs": native_crs,
        "id_col": id_col,
        "hru_count": hru_count,
        "bbox": {
            "minx": float(wgs84_bounds[0]),
            "miny": float(wgs84_bounds[1]),
            "maxx": float(wgs84_bounds[2]),
            "maxy": float(wgs84_bounds[3]),
        },
        "bbox_buffered": buffered,
        "buffer_deg": buffer_deg,
    }


def _sha256(path: Path) -> str:
    """Compute SHA-256 of a file, or of all files in a directory (e.g. .gdb)."""
    h = hashlib.sha256()
    if path.is_dir():
        for child in sorted(path.rglob("*"), key=lambda p: str(p)):
            if child.is_file():
                h.update(str(child.relative_to(path)).encode())
                with child.open("rb") as f:
                    for chunk in iter(lambda: f.read(1 << 20), b""):
                        h.update(chunk)
    else:
        with path.open("rb") as f:
            for chunk in iter(lambda: f.read(1 << 20), b""):
                h.update(chunk)
    return h.hexdigest()


# ---------------------------------------------------------------------------
# Output writers
# ---------------------------------------------------------------------------


def _write_fabric_json(workdir: Path, fabric_meta: dict) -> None:
    path = workdir / "fabric.json"
    path.write_text(json.dumps(fabric_meta, indent=2))


def _write_manifest(workdir: Path, fabric_meta: dict) -> None:
    """Write `manifest.json`, preserving any prior `sources` and `steps`.

    Re-running validate must NOT clobber the provenance recorded by
    prior fetch/agg runs (issue #97). When `manifest.json` exists and is
    parseable:

    - ``created_utc`` is preserved (true first-creation time).
    - ``sources`` and ``steps`` are carried over byte-for-byte.
    - ``fabric`` block is refreshed (fabric file may have changed).
    - ``nhf_spatial_targets_version`` is refreshed (validate "blesses"
      the manifest with the current pipeline version).
    - ``last_validated_utc`` is set to now so operators can tell when
      the last validate happened.

    When `manifest.json` is absent OR cannot be parsed, a fresh skeleton
    is written. (We don't try to recover a partially-corrupt manifest;
    the operator's options at that point are to inspect the file or
    delete it.)

    Write is atomic (tempfile + rename) so a concurrent reader never
    sees a half-written manifest.
    """
    now_utc = datetime.now(timezone.utc).isoformat()
    fabric_block = {
        "path": fabric_meta["path"],
        "sha256": fabric_meta["sha256"],
        "crs": fabric_meta["crs"],
        "id_col": fabric_meta["id_col"],
        "hru_count": fabric_meta["hru_count"],
    }

    path = workdir / "manifest.json"
    preserved: dict = {}
    if path.exists():
        try:
            preserved = json.loads(path.read_text())
        except json.JSONDecodeError as exc:
            logger.warning(
                "manifest.json in %s could not be parsed (%s); writing a "
                "fresh skeleton. Inspect the file manually if you need "
                "to recover any prior provenance.",
                workdir,
                exc,
            )
            preserved = {}

    manifest = {
        "created_utc": preserved.get("created_utc") or now_utc,
        "last_validated_utc": now_utc,
        "nhf_spatial_targets_version": __version__,
        "fabric": fabric_block,
        "sources": preserved.get("sources") or {},
        "steps": preserved.get("steps") or [],
    }

    tmp_fd, tmp_path = tempfile.mkstemp(dir=path.parent, suffix=".json.tmp")
    try:
        with os.fdopen(tmp_fd, "w") as f:
            json.dump(manifest, f, indent=2)
        Path(tmp_path).replace(path)
    except BaseException:
        Path(tmp_path).unlink(missing_ok=True)
        raise
